language: java
jdk:
  - oraclejdk8
sudo: false
script:
  - mvn package
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ls -al target
  - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/cobertura.xml